services:
  backend:
    build: ./backend
    container_name: febc_backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: febc_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_media:
